import type { NextPage } from "next";
import Head from "next/head";
import Nav from "../components/Navigation/Nav";
import NFTTraitsList from "../components/NFTAttributesList/NFTTraitsList";
import Pagination from "../components/NFTAttributesList/Pagination";
import ParseSettings from "../components/ParseSettings/ParseSettings";
import { Trait } from "../utils/services/IPFSService";
import { ELEMENTS_PER_PAGE } from "../utils/Settings";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const allTraitsQuery = trpc.ipfs.getTraits.useQuery(
    "bafybeievpwedrt7soo6nbgkdttmjjmpkcsjkzpyaz4zox74fr45blo5boe"
  );
  let allTraits: Trait[] = allTraitsQuery.data?.traits ?? [];

  return (
    <>
      <Head>
        <title>YattaDeSuniper - NFT Metadata parser</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav></Nav>
      <ParseSettings></ParseSettings>
      <NFTTraitsList></NFTTraitsList>
      {allTraits.length > ELEMENTS_PER_PAGE && <Pagination></Pagination>}
    </>
  );
};

export default Home;
