import type { NextPage } from "next";
import Head from "next/head";
import Nav from "../components/Navigation/Nav";
import ParseSettings from "../components/ParseSettings/ParseSettings";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  // const metadata = trpc.ipfs.metadata.useQuery();

  return (
    <>
      <Head>
        <title>YattaDeSuniper - NFT Metadata parser</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav></Nav>
      <ParseSettings></ParseSettings>
    </>
  );
};

export default Home;
