import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { string } from "zod";
import Nav from "../components/Navigation/Nav";
import NFTTraitsList from "../components/NFTAttributesList/NFTTraitsList";
import Pagination from "../components/NFTAttributesList/Pagination";
import ParseSettings from "../components/ParseSettings/ParseSettings";
import { Trait } from "../utils/services/IPFSService";
import { ELEMENTS_PER_PAGE } from "../utils/app-settings";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  let [CID, setCID] = useState("");
  let [supply, setSupply] = useState(0);

  const handleParseState = (parsedCID: string, parsedSupply: number) => {
    setCID(parsedCID);
    setSupply(parsedSupply);
  };

  const allTraitsQuery = trpc.ipfs.getTraits.useQuery(CID);
  let allTraits: Trait[] = allTraitsQuery.data?.traits ?? [];

  return (
    <>
      <Head>
        <title>YattaDeSuniper - NFT Metadata parser</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav></Nav>
      <ParseSettings parseStateHandler={handleParseState} />
      <NFTTraitsList CID={CID}></NFTTraitsList>
      {allTraits.length > ELEMENTS_PER_PAGE && (
        <Pagination traitsCount={allTraits.length} />
      )}
    </>
  );
};

export default Home;
